import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.error("GEMINI_API_KEY is not configured in environment variables");
      return NextResponse.json(
        { error: "Google Gemini API key is not configured." },
        { status: 500 }
      );
    }

    const body = await request.json();
    const { contents } = body;

    if (!contents || !Array.isArray(contents)) {
      return NextResponse.json(
        { error: "Invalid request body: 'contents' must be a valid array." },
        { status: 400 }
      );
    }

    const systemInstruction = {
      parts: [
        {
          text: "You are UniAI, the premium, intelligent AI Movie Assistant for Unimovies (designed & developed by Sounak Guin). Your job is to help users discover movies, TV shows, anime, and documentaries. \n\n" +
                "GUIDELINES:\n" +
                "1. Keep your replies concise, friendly, and engaging. Avoid long paragraphs; use spacing, bullet points, and emoji to make messages readable.\n" +
                "2. When recommending movies, ALWAYS format the titles in bold (e.g. **Interstellar**, **Attack on Titan**).\n" +
                "3. Try to briefly explain *why* you are suggesting each title (e.g., matching the genre, mood, director, or tone requested).\n" +
                "4. When referring to the current time/year, the year is 2026. Recommend recent titles from 2024, 2025, and upcoming ones in 2026 where appropriate.\n" +
                "5. Never output HTML tags. If you want to list items, use markdown bullets (- or *).\n" +
                "6. If asked about Unimovies, explain that it is a sleek, modern platform for discovering the latest trending and top-rated movies, TV shows, anime, and celebrity information.\n" +
                "7. Be polite and conversational, but stay focused on entertainment, movies, and TV shows. If the user asks a completely unrelated question (e.g. programming or cooking), politely guide them back to movies."
        }
      ]
    };

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents,
          systemInstruction,
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 800,
          }
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gemini API Error:", errorText);
      return NextResponse.json(
        { error: "Error communicating with the Gemini AI service." },
        { status: response.status }
      );
    }

    const data = await response.json();
    const replyText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!replyText) {
      console.error("Gemini API returned an empty reply:", JSON.stringify(data));
      return NextResponse.json(
        { error: "No response text generated by the model." },
        { status: 500 }
      );
    }

    return NextResponse.json({ reply: replyText });
  } catch (error) {
    console.error("Gemini Route Exception:", error);
    return NextResponse.json(
      { error: "An unexpected server error occurred." },
      { status: 500 }
    );
  }
}

// Block other methods
export async function GET() {
  return NextResponse.json({ error: "Method not allowed" }, { status: 405 });
}
